
CREATE TABLE POKEMON (
    ID INTEGER,
    NAME VARCHAR(100), 
    POKEMONTYPE_ID INTEGER, 
    PRIMARY KEY(ID),
    CONSTRAINT FK_POKEMONTYPE FOREIGN KEY(POKEMONTYPE_ID) REFERENCES POKEMONTYPE(ID)
);
