
CREATE TABLE POKEMON (ID INTEGER NOT NULL, NAME VARCHAR NOT NULL, POKEMONTYPE_ID INTEGER, PRIMARY KEY (ID));

ALTER TABLE POKEMON ADD CONSTRAINT FK_POKEMON_POKEMONTYPE_ID FOREIGN KEY (POKEMONTYPE_ID) REFERENCES POKEMONTYPE (ID);
